# https://github.com/jojomi/docker-hugo

hugo:
  image: jojomi/hugo:0.57.2
  volumes:
     - ./:/src
     - ./public:/output
       
    # This can be used to test the example site
    #- ./themes/academic/exampleSite/:/src
    #- ./themes/:/src/themes/
  environment:
    - HUGO_BASEURL=0.0.0.0
    - HUGO_WATCH=true
    - HUGO_THEME=academic
    # - HUGO_REFRESH_TIME=3600
    # - HUGO_DESTINATION="/output"
  ports:
    - "1313:1313"

# web:
#   image: jojomi/nginx-static
#   volumes:
#     - hugo-academic-kickstart-out:/var/www
#   ports:
#     - "80:80"
#   restart: always
