[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.49"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_VERSION = "0.49"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
